# Generated by Django 3.0.2 on 2020-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourcompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='latest_pics')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=16)),
                ('facilitator', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField()),
                ('venue', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='MeetupsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='meetups_pics')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=16)),
                ('facilitator', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField()),
                ('venue', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='upcoming_pics')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=16)),
                ('facilitator', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField()),
                ('venue', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='workshops_pics')),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=16)),
                ('facilitator', models.CharField(max_length=55)),
                ('date_created', models.DateTimeField()),
                ('venue', models.CharField(max_length=55)),
            ],
        ),
    ]
